galaxy_info:
  author: Thiago Gomes
  description: A simple ansible role to restart the tomcat service
  company:
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
      - all
    - name: Debian
      versions:
      - all
  galaxy_tags:
    - system
dependencies: []
