
- block :
  - name: Ansible delete file wildcard
    find:
      paths: /home/ubuntu/Kartik
      patterns: "te*.txt"
      use_regex: true
    register: wildcard_files_to_delete

  - name: Ansible remove file wildcard
    file:
      path: "{{ item.path }}"
      state: absent
    loop: "{{ wildcard_files_to_delete.files }}"
